sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install cookiecutter
script:
  - cookiecutter --no-input gh:rrwen/cookiecutter-latex-ryerson font_style="Liberation Sans"
  - cd sample
  - chmod +x make.sh
  - ./make.sh
